using System.Globalization;
using System.Text;
using Microsoft.Data.SqlClient;

if (args.Length < 1)
{
    Console.Error.WriteLine("""
        HealUp.DataExport — writes INSERT T-SQL from your local (or any) SQL Server database.

        Usage:
          dotnet run --project HealUp.DataExport -- "<LOCAL_CONNECTION_STRING>" [output.sql]

        Example:
          dotnet run --project HealUp.DataExport -- "Server=TUSK\\SQLEXPRESS;Database=healupproject;Trusted_Connection=True;TrustServerCertificate=True;Encrypt=False;" healup-data.sql

        Then open healup-data.sql, review it, and paste into MonsterASP "Run T-SQL" (may need to split very large files).

        WARNING: This script DELETEs all rows in HealUp tables on the target DB before INSERTing.
        Only run against the online DB if you intend to replace its data.
        """);
    return 1;
}

var connectionString = args[0];
var outPath = args.Length >= 2 ? args[1] : Path.Combine(Directory.GetCurrentDirectory(), "healup-data-export.sql");

var deleteOrder = new[]
{
    "order_items",
    "orders",
    "response_medicines",
    "pharmacy_responses",
    "request_medicines",
    "requests",
    "notifications",
    "patients",
    "pharmacies",
    "admins"
};

var insertOrder = new[]
{
    "patients",
    "admins",
    "pharmacies",
    "requests",
    "request_medicines",
    "pharmacy_responses",
    "response_medicines",
    "orders",
    "order_items",
    "notifications"
};

await using var conn = new SqlConnection(connectionString);
await conn.OpenAsync();

var sb = new StringBuilder(64_000);
sb.AppendLine("-- HealUp data export (generated by HealUp.DataExport)");
sb.AppendLine("-- Run on TARGET database (e.g. MonsterASP) after schema exists (migrations applied).");
sb.AppendLine("-- Deletes existing data in these tables, then inserts with original IDs.");
sb.AppendLine();
sb.AppendLine("SET NOCOUNT ON;");
sb.AppendLine("SET XACT_ABORT ON;");
sb.AppendLine();
sb.AppendLine("BEGIN TRANSACTION;");
sb.AppendLine();

foreach (var t in deleteOrder)
{
    sb.AppendLine($"DELETE FROM [{t}];");
}

sb.AppendLine();

foreach (var table in insertOrder)
{
    await AppendTableInsertsAsync(conn, table, sb);
}

sb.AppendLine("COMMIT TRANSACTION;");
// Note: do not use GO here — many hosted "Run T-SQL" tools execute one batch only.

await File.WriteAllTextAsync(outPath, sb.ToString(), Encoding.UTF8);
Console.WriteLine($"Wrote: {outPath} ({new FileInfo(outPath).Length / 1024} KB approx)");
return 0;

static async Task AppendTableInsertsAsync(SqlConnection conn, string table, StringBuilder sb)
{
    await using var cmd = new SqlCommand($"SELECT * FROM [{table}] ORDER BY [Id]", conn);
    await using var reader = await cmd.ExecuteReaderAsync();
    if (!reader.HasRows)
    {
        sb.AppendLine($"-- (no rows in [{table}])");
        sb.AppendLine();
        return;
    }

    var colNames = new string[reader.FieldCount];
    for (var i = 0; i < reader.FieldCount; i++)
        colNames[i] = reader.GetName(i);

    var bracketedCols = string.Join(", ", colNames.Select(c => $"[{c}]"));

    sb.AppendLine($"SET IDENTITY_INSERT [{table}] ON;");
    while (await reader.ReadAsync())
    {
        var vals = new string[reader.FieldCount];
        for (var i = 0; i < reader.FieldCount; i++)
        {
            var v = reader.GetValue(i);
            vals[i] = FormatSqlLiteral(v, reader.GetFieldType(i));
        }

        sb.AppendLine($"INSERT INTO [{table}] ({bracketedCols}) VALUES ({string.Join(", ", vals)});");
    }

    sb.AppendLine($"SET IDENTITY_INSERT [{table}] OFF;");
    sb.AppendLine();
}

static string FormatSqlLiteral(object value, Type fieldType)
{
    if (value is DBNull)
        return "NULL";

    var t = Nullable.GetUnderlyingType(fieldType) ?? fieldType;

    if (t == typeof(string))
        return "N'" + ((string)value).Replace("'", "''") + "'";

    if (t == typeof(bool))
        return (bool)value ? "1" : "0";

    if (t == typeof(byte) || t == typeof(short) || t == typeof(int) || t == typeof(long))
        return Convert.ToString(value, CultureInfo.InvariantCulture)!;

    if (t == typeof(decimal))
        return ((decimal)value).ToString(CultureInfo.InvariantCulture);

    if (t == typeof(double))
        return ((double)value).ToString(CultureInfo.InvariantCulture);

    if (t == typeof(float))
        return ((float)value).ToString(CultureInfo.InvariantCulture);

    if (t == typeof(DateTime))
    {
        var dt = (DateTime)value;
        return "'" + dt.ToString("yyyy-MM-dd HH:mm:ss.fff", CultureInfo.InvariantCulture) + "'";
    }

    if (t == typeof(DateTimeOffset))
    {
        var dto = (DateTimeOffset)value;
        return "'" + dto.ToString("yyyy-MM-dd HH:mm:ss.fff zzz", CultureInfo.InvariantCulture).Replace(" ", "") + "'";
    }

    if (t == typeof(Guid))
        return "N'" + ((Guid)value).ToString("D") + "'";

    if (t == typeof(byte[]))
        throw new NotSupportedException($"Column type byte[] not supported in export (table binary data).");

    return "N'" + value.ToString()!.Replace("'", "''") + "'";
}
