using System.Globalization;
using System.Text;
using System.Text.Json;
using Microsoft.Data.SqlClient;

const string defaultOutFile = "healup-data-export.sql";

if (args.Length < 1 || args[0] is "-h" or "--help" or "/?")
{
    PrintHelp();
    return args.Length < 1 ? 1 : 0;
}

// --show-connection <path-to-appsettings.json>  → print masked connection (no export)
if (args[0] == "--show-connection" && args.Length >= 2)
{
    var path = Path.GetFullPath(args[1]);
    var cs = ReadConnectionStringFromJsonFile(path);
    Console.WriteLine($"File: {path}");
    Console.WriteLine();
    Console.WriteLine("Connection string (password masked):");
    Console.WriteLine(MaskConnectionString(cs));
    return 0;
}

string connectionString;
string outPath;

if (args[0] == "--config" && args.Length >= 2)
{
    var jsonPath = Path.GetFullPath(args[1]);
    connectionString = ReadConnectionStringFromJsonFile(jsonPath);
    outPath = args.Length >= 3 ? args[2]! : Path.Combine(Directory.GetCurrentDirectory(), defaultOutFile);
    Console.WriteLine($"Using connection from: {jsonPath}");
    Console.WriteLine($"Target (masked): {MaskConnectionString(connectionString)}");
    Console.WriteLine();
}
else if (File.Exists(args[0]) && args[0].EndsWith(".json", StringComparison.OrdinalIgnoreCase))
{
    var jsonPath = Path.GetFullPath(args[0]);
    connectionString = ReadConnectionStringFromJsonFile(jsonPath);
    outPath = args.Length >= 2 ? args[1]! : Path.Combine(Directory.GetCurrentDirectory(), defaultOutFile);
    Console.WriteLine($"Using connection from: {jsonPath}");
    Console.WriteLine($"Target (masked): {MaskConnectionString(connectionString)}");
    Console.WriteLine();
}
else
{
    connectionString = args[0];
    outPath = args.Length >= 2 ? args[1]! : Path.Combine(Directory.GetCurrentDirectory(), defaultOutFile);
}

var deleteOrder = new[]
{
    "order_items",
    "orders",
    "response_medicines",
    "pharmacy_responses",
    "request_medicines",
    "requests",
    "notifications",
    "patients",
    "pharmacies",
    "admins"
};

var insertOrder = new[]
{
    "patients",
    "admins",
    "pharmacies",
    "requests",
    "request_medicines",
    "pharmacy_responses",
    "response_medicines",
    "orders",
    "order_items",
    "notifications"
};

await using var conn = new SqlConnection(connectionString);
await conn.OpenAsync();

var sb = new StringBuilder(64_000);
sb.AppendLine("-- HealUp data export (generated by HealUp.DataExport)");
sb.AppendLine("-- Run on TARGET database (e.g. MonsterASP) after schema exists (migrations applied).");
sb.AppendLine("-- Deletes existing data in these tables, then inserts with original IDs.");
sb.AppendLine();
sb.AppendLine("SET NOCOUNT ON;");
sb.AppendLine("SET XACT_ABORT ON;");
sb.AppendLine();
sb.AppendLine("BEGIN TRANSACTION;");
sb.AppendLine();

foreach (var t in deleteOrder)
{
    sb.AppendLine($"DELETE FROM [{t}];");
}

sb.AppendLine();

foreach (var table in insertOrder)
{
    await AppendTableInsertsAsync(conn, table, sb);
}

sb.AppendLine("COMMIT TRANSACTION;");

await File.WriteAllTextAsync(outPath, sb.ToString(), Encoding.UTF8);
Console.WriteLine($"Wrote: {outPath} ({new FileInfo(outPath).Length / 1024} KB approx)");
return 0;

static void PrintHelp()
{
    Console.WriteLine(
        """
        HealUp.DataExport — writes INSERT T-SQL from a SQL Server database (usually your local DB).

        WHERE IS THE CONNECTION STRING?
        ───────────────────────────────
        • Local dev:  HealUp.Api/appsettings.Development.json  →  "ConnectionStrings": { "DefaultConnection": "..." }
        • Example:    HealUp.Api/appsettings.Development.example.json (copy to Development and edit)
        • Production: MonsterASP panel / appsettings on the server (do not commit passwords to Git)

        USAGE
        ─────
        1) Point at your JSON file (easiest):
             dotnet run --project HealUp.DataExport -- --config "..\\HealUp.Api\\appsettings.Development.json"
             dotnet run --project HealUp.DataExport -- "..\\HealUp.Api\\appsettings.Development.json"

        2) Paste the full connection string (same text as in JSON):
             dotnet run --project HealUp.DataExport -- "Server=...;Database=...;..."  [output.sql]

        3) Only SHOW the connection string from a file (password masked):
             dotnet run --project HealUp.DataExport -- --show-connection "..\\HealUp.Api\\appsettings.Development.json"

        WARNING: Exported script DELETEs HealUp tables then INSERTs. Only run the .sql on the DB you intend to replace.
        """);
}

static string ReadConnectionStringFromJsonFile(string fullPath)
{
    if (!File.Exists(fullPath))
        throw new FileNotFoundException($"JSON file not found: {fullPath}");

    var json = File.ReadAllText(fullPath);
    using var doc = JsonDocument.Parse(json);
    if (!doc.RootElement.TryGetProperty("ConnectionStrings", out var cs))
        throw new InvalidOperationException("Missing 'ConnectionStrings' section in JSON.");

    if (!cs.TryGetProperty("DefaultConnection", out var def))
        throw new InvalidOperationException("Missing 'ConnectionStrings:DefaultConnection' in JSON.");

    var s = def.GetString();
    if (string.IsNullOrWhiteSpace(s))
        throw new InvalidOperationException("'DefaultConnection' is empty.");

    return s;
}

static string MaskConnectionString(string connectionString)
{
    var parts = connectionString.Split(';', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
    return string.Join(
        "; ",
        parts.Select(p =>
        {
            var eq = p.IndexOf('=');
            if (eq < 0) return p;
            var key = p[..eq].Trim();
            if (key.Equals("Password", StringComparison.OrdinalIgnoreCase) ||
                key.Equals("Pwd", StringComparison.OrdinalIgnoreCase))
                return $"{key}=***";
            return p;
        })) + ";";
}

static async Task AppendTableInsertsAsync(SqlConnection conn, string table, StringBuilder sb)
{
    await using var cmd = new SqlCommand($"SELECT * FROM [{table}] ORDER BY [Id]", conn);
    await using var reader = await cmd.ExecuteReaderAsync();
    if (!reader.HasRows)
    {
        sb.AppendLine($"-- (no rows in [{table}])");
        sb.AppendLine();
        return;
    }

    var colNames = new string[reader.FieldCount];
    for (var i = 0; i < reader.FieldCount; i++)
        colNames[i] = reader.GetName(i);

    var bracketedCols = string.Join(", ", colNames.Select(c => $"[{c}]"));

    sb.AppendLine($"SET IDENTITY_INSERT [{table}] ON;");
    while (await reader.ReadAsync())
    {
        var vals = new string[reader.FieldCount];
        for (var i = 0; i < reader.FieldCount; i++)
        {
            var v = reader.GetValue(i);
            vals[i] = FormatSqlLiteral(v, reader.GetFieldType(i));
        }

        sb.AppendLine($"INSERT INTO [{table}] ({bracketedCols}) VALUES ({string.Join(", ", vals)});");
    }

    sb.AppendLine($"SET IDENTITY_INSERT [{table}] OFF;");
    sb.AppendLine();
}

static string FormatSqlLiteral(object value, Type fieldType)
{
    if (value is DBNull)
        return "NULL";

    var t = Nullable.GetUnderlyingType(fieldType) ?? fieldType;

    if (t == typeof(string))
        return "N'" + ((string)value).Replace("'", "''") + "'";

    if (t == typeof(bool))
        return (bool)value ? "1" : "0";

    if (t == typeof(byte) || t == typeof(short) || t == typeof(int) || t == typeof(long))
        return Convert.ToString(value, CultureInfo.InvariantCulture)!;

    if (t == typeof(decimal))
        return ((decimal)value).ToString(CultureInfo.InvariantCulture);

    if (t == typeof(double))
        return ((double)value).ToString(CultureInfo.InvariantCulture);

    if (t == typeof(float))
        return ((float)value).ToString(CultureInfo.InvariantCulture);

    if (t == typeof(DateTime))
    {
        var dt = (DateTime)value;
        return "'" + dt.ToString("yyyy-MM-dd HH:mm:ss.fff", CultureInfo.InvariantCulture) + "'";
    }

    if (t == typeof(DateTimeOffset))
    {
        var dto = (DateTimeOffset)value;
        return "'" + dto.ToString("yyyy-MM-dd HH:mm:ss.fff zzz", CultureInfo.InvariantCulture).Replace(" ", "") + "'";
    }

    if (t == typeof(Guid))
        return "N'" + ((Guid)value).ToString("D") + "'";

    if (t == typeof(byte[]))
        throw new NotSupportedException($"Column type byte[] not supported in export (table binary data).");

    return "N'" + value.ToString()!.Replace("'", "''") + "'";
}
